monolog:
    channels:
        # - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - operational # Custom channel for payment logs (API, transactions, Redis, security)

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

            # ✅ OPERATIONAL LOGGING FOR PAYMENTS
            operational_log:
                type: stream
                path: "%kernel.logs_dir%/payment.log"
                level: info  # Logs info, debug & error
                channels: ["operational"] 

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

            # ✅ OPERATIONAL LOGGING FOR PAYMENTS IN TEST ENVIRONMENT
            operational_log:
                type: stream
                path: "%kernel.logs_dir%/payment.log"
                level: info
                channels: ["operational"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # Prevents memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json

            # ✅ OPERATIONAL LOGGING FOR PAYMENTS IN PRODUCTION
            operational_log:
                type: stream
                path: "%kernel.logs_dir%/payment.log"
                level: info
                channels: ["operational"]
