nelmio_api_doc:
  documentation:
    info:
      title: Simplified Payment Gateway
      description: A simplified payment gateway integration with multiple providers
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
    security:
      - Bearer: []
  areas:
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
