version: "3.8"

services:
  # PHP + Symfony App
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: payment_gateway_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
    networks:
      - payment_network
    environment:
      APP_ENV: dev
      PHP_EXTENSION: redis

  # NGINX Web Server
  nginx:
    image: nginx:latest
    container_name: payment_gateway_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - payment_network

  # Redis (For caching, idempotency, and load balancing)
  redis:
    image: redis:alpine
    container_name: payment_gateway_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - payment_network

networks:
  payment_network:
    driver: bridge
